- name: Demo on loops
  hosts: localhost
  connection: local
  tasks:
    - name: Print Hello Universe
      ansible.builtin.debug:
        msg: Fruit Name - {{ item }}
      loop:
        - apple
        - orange
        - grape
        - watermelon